name: flutter_web_bluetooth
description: A library to use the web bluetooth api in your web project. Will play nice if used IO projects.
version: 0.0.4
homepage: https://github.com/jeroen1602/flutter_web_bluetooth/
repository: https://github.com/jeroen1602/flutter_web_bluetooth/
issue_tracker: https://github.com/jeroen1602/flutter_web_bluetooth/issues/

environment:
  sdk: ">=3.4.0-0 <4.0.0"

dependencies:
  js: '>=0.6.3 <2.0.0'
  rxdart: '>=0.27.0 <2.0.0'

dev_dependencies:
  test: '>=1.17.4'
  lints: '>=1.0.0'